import { SiteClient } from 'datocms-client';

const communityRequest = async (req, res) => {
  if (req.method === 'POST') {
    const client = new SiteClient(process.env.NEXT_PUBLIC_DATO_API_KEY);

    const { title, imageUrl, creatorSlug } = req.body;
  
    const record = await client.items.create({
      itemType: '2099', // Community Model ID generated by DatoCMS
      title,
      imageUrl,
      creatorSlug,
    });
  
    return res.status(201).json(record);
  }

  return res.status(404).json({
    message: 'Em desenvolvimento',
  });
};

export default communityRequest;
